version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "80:be:b6:62:97:d3:95:f1:5a:8c:2d:86:55:eb:1c:21"
      - node/with-cache:
          steps:
            - run: git config --local user.email "mateusz.bieda95@gmail.com"
            - run: git config --local user.name "mateBe95"
            - run: npm install
            - run: npm run deploy
workflows:
  build-and-test:
    jobs:
      - build-and-test